language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '8.1'
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev